# Objevtive : Market Basket Analysis

#### This File contains information about Customers buying different grocery items at a Mall.
#### Features: 
##### Currently we dont have any features and we will make them in Data Preprocessing
##### We have to first analyse this data and as we can see that each row is a transaction we have to make columns by items present in the market and map all the transactions to them so we can relate and associate different rules

### Steps: 
* Importing necessary Libraries and Data
* Data Preprocessing
* Data Encoding
* Apriori Algorithm
* Association Rules
* Association Rules (Without Mineral Water)

# Importing Necessary Libraries and Data

pip install mlxtend

In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
#Load Dataset
df = pd.read_csv('C:/Users/Hassan Ahmed/Desktop/Data Science Cohort-1 FTI/Market_Basket_Optimisation.csv',header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,7501,5747,4389,3345,2529,1864,1369,981,654,395,256,154,87,47,25,8,4,4,3,1
unique,115,117,115,114,110,106,102,98,88,80,66,50,43,28,19,8,3,3,3,1
top,mineral water,mineral water,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea,green tea,low fat yogurt,green tea,green tea,green tea,magazines,salmon,frozen smoothie,protein bar,cereals,olive oil
freq,577,484,375,201,153,107,96,67,57,31,22,15,8,4,3,1,2,2,1,1

# Data Preprocessing

In [3]:
# making each customers shopping items an identical list
transactions = []
for a in range(0, 7501):
    transactions.append([str(df.values[a,b]).strip() for b in range(0, 20)])

# conveting it into an numpy array
transactions = np.array(transactions)

# checking the shape of the array
print(transactions.shape)

(7501, 20)

# Data Encoding

In [4]:
trans_enc = TransactionEncoder()
Enc_data = trans_enc.fit_transform(transactions)
Enc_data = pd.DataFrame(Enc_data, columns = trans_enc.columns_)

# getting the shape of the data
Enc_data.columns=Enc_data.columns.str.strip()
Enc_data.shape

(7501, 120)

In [5]:
Enc_data.head()

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [6]:
def encode_units(x):
    if x==False:
        return 0
    if x==True:
        return 1

basket_sets=Enc_data.applymap(encode_units)
basket_sets.drop("nan",inplace=True,axis=1)

# Apriori Algorithm

Generating Frequent item set with a chosen support threshold value
We can now generate frequent item sets that have a support of at least 5%

In [7]:
frequent_itemsets = apriori(basket_sets, min_support = 0.05, use_colnames=True)

# Association Rules

Generating Rules
The final step is to generate the rules with their corresponding support, confidence and lift.

In [8]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(mineral water),(chocolate),0.238368,0.163845,0.052660,0.220917,1.348332,0.013604,1.073256
1,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,0.013604,1.122357
2,(eggs),(mineral water),0.179709,0.238368,0.050927,0.283383,1.188845,0.008090,1.062815
3,(mineral water),(eggs),0.238368,0.179709,0.050927,0.213647,1.188845,0.008090,1.043158
4,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,0.018223,1.159314
5,(mineral water),(spaghetti),0.238368,0.174110,0.059725,0.250559,1.439085,0.018223,1.102008

##### Unique Combinations

In [9]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
# getting th item sets with length = 2 and support more han 10%
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.05) ].reset_index(drop=True)

    support                    itemsets  length
0  0.052660  (mineral water, chocolate)       2
1  0.050927       (eggs, mineral water)       2
2  0.059725  (spaghetti, mineral water)       2

##### Analysis
1. We can see that there are quite a few rules with a high lift value which means that it occurs more frequently than would be expected given the number of transaction and product combinations.
2. We can also see several where the confidence is high as well. This part of the analysis is where the domain knowledge will come in handy.

We can filter the dataframe and, look for a lift of 1 and confidence 0.2.

In [10]:
rules[ (rules['lift'] >= 1) &
       (rules['confidence'] >= 0.3) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,0.013604,1.122357
4,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,0.018223,1.159314

##### Results of Analysis
1. In looking at the rules, it seems that the mineral water and spaghetti as well as chocolate and mineral water are purchased together more often.

# Association Rules (Without Mineral Water)

#### As we can see that ** mineral water ** is constant in all our rules so by excluding this we are now going to analyse other rules as well.

In [11]:
basket_sets.drop("mineral water",inplace=True,axis=1)

In [12]:
frequent_itemsets1 = apriori(basket_sets, min_support = 0.02, use_colnames=True)

In [13]:
rules1 = association_rules(frequent_itemsets1, metric="confidence", min_threshold=0.2)
rules1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,0.013128,1.224818
1,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,0.007096,1.108844
2,(burgers),(spaghetti),0.087188,0.174110,0.021464,0.246177,1.413918,0.006283,1.095602
3,(chocolate),(eggs),0.163845,0.179709,0.033196,0.202604,1.127397,0.003751,1.028711
4,(french fries),(chocolate),0.170911,0.163845,0.034395,0.201248,1.228284,0.006393,1.046827
5,(chocolate),(french fries),0.163845,0.170911,0.034395,0.209927,1.228284,0.006393,1.049383
6,(frozen vegetables),(chocolate),0.095321,0.163845,0.022930,0.240559,1.468215,0.007312,1.101015
7,(ground beef),(chocolate),0.098254,0.163845,0.023064,0.234735,1.432669,0.006965,1.092635
8,(milk),(chocolate),0.129583,0.163845,0.032129,0.247942,1.513276,0.010898,1.111823
9,(spaghetti),(chocolate),0.174110,0.163845,0.039195,0.225115,1.373952,0.010668,1.079070
10,(chocolate),(spaghetti),0.163845,0.174110,0.039195,0.239219,1.373952,0.010668,1.085581
11,(french fries),(eggs),0.170911,0.179709,0.036395,0.212949,1.184961,0.005681,1.042232
12,(eggs),(french fries),0.179709,0.170911,0.036395,0.202522,1.184961,0.005681,1.039640
13,(frozen vegetables),(eggs),0.095321,0.179709,0.021730,0.227972,1.268559,0.004600,1.062514
14,(milk),(eggs),0.129583,0.179709,0.030796,0.237654,1.322437,0.007509,1.076009
15,(pancakes),(eggs),0.095054,0.179709,0.021730,0.228612,1.272118,0.004648,1.063395
16,(eggs),(spaghetti),0.179709,0.174110,0.036528,0.203264,1.167446,0.005239,1.036592
17,(spaghetti),(eggs),0.174110,0.179709,0.036528,0.209801,1.167446,0.005239,1.038081
18,(green tea),(french fries),0.132116,0.170911,0.028530,0.215943,1.263488,0.005950,1.057436
19,(pancakes),(french fries),0.095054,0.170911,0.020131,0.211781,1.239135,0.003885,1.051852
20,(frozen vegetables),(milk),0.095321,0.129583,0.023597,0.247552,1.910382,0.011245,1.156781
21,(frozen vegetables),(spaghetti),0.095321,0.174110,0.027863,0.292308,1.678867,0.011267,1.167018
22,(green tea),(spaghetti),0.132116,0.174110,0.026530,0.200807,1.153335,0.003527,1.033405
23,(ground beef),(milk),0.098254,0.129583,0.021997,0.223881,1.727704,0.009265,1.121499
24,(spaghetti),(ground beef),0.174110,0.098254,0.039195,0.225115,2.291162,0.022088,1.163716
25,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997
26,(spaghetti),(milk),0.174110,0.129583,0.035462,0.203675,1.571779,0.012900,1.093043
27,(milk),(spaghetti),0.129583,0.174110,0.035462,0.273663,1.571779,0.012900,1.137061
28,(olive oil),(spaghetti),0.065858,0.174110,0.022930,0.348178,1.999758,0.011464,1.267048
29,(pancakes),(spaghetti),0.095054,0.174110,0.025197,0.265077,1.522468,0.008647,1.123778
30,(shrimp),(spaghetti),0.071457,0.174110,0.021197,0.296642,1.703760,0.008756,1.174209
31,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117

##### Unique Combinations

In [14]:
frequent_itemsets1['length'] = frequent_itemsets1['itemsets'].apply(lambda x: len(x))
# getting th item sets with length = 2 and support more han 10%
frequent_itemsets1[(frequent_itemsets1['length'] == 2) &
                   (frequent_itemsets1['support'] >= 0.02)].reset_index(drop=True)

     support                        itemsets  length
0   0.028796                 (burgers, eggs)       2
1   0.021997         (burgers, french fries)       2
2   0.021464            (burgers, spaghetti)       2
3   0.033196               (eggs, chocolate)       2
4   0.034395       (french fries, chocolate)       2
5   0.022930  (frozen vegetables, chocolate)       2
6   0.023464          (green tea, chocolate)       2
7   0.023064        (ground beef, chocolate)       2
8   0.032129               (milk, chocolate)       2
9   0.039195          (spaghetti, chocolate)       2
10  0.036395            (french fries, eggs)       2
11  0.021730       (eggs, frozen vegetables)       2
12  0.025463               (green tea, eggs)       2
13  0.030796                    (eggs, milk)       2
14  0.021730                (pancakes, eggs)       2
15  0.036528               (eggs, spaghetti)       2
16  0.028530       (green tea, french fries)       2
17  0.023730            (french fries, milk)       2
18  0.020131        (pancakes, french fries)       2
19  0.027596       (french fries, spaghetti)       2
20  0.023597       (frozen vegetables, milk)       2
21  0.027863  (spaghetti, frozen vegetables)       2
22  0.026530          (green tea, spaghetti)       2
23  0.021997             (ground beef, milk)       2
24  0.039195        (spaghetti, ground beef)       2
25  0.035462               (spaghetti, milk)       2
26  0.022930          (spaghetti, olive oil)       2
27  0.025197           (pancakes, spaghetti)       2
28  0.021197             (shrimp, spaghetti)       2
29  0.020931           (tomatoes, spaghetti)       2

##### Analysis
1. We can see that there are quite a few rules with a high lift value which means that it occurs more frequently than would be expected given the number of transaction and product combinations.
2. We can also see several where the confidence is high as well. This part of the analysis is where the domain knowledge will come in handy.

We can filter the dataframe and, look for a lift of 1.5 and confidence 0.2.

In [15]:
rules1[ (rules1['lift'] >= 1.5) &
       (rules1['confidence'] >= 0.2) ].reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,0.013128,1.224818
1,(milk),(chocolate),0.129583,0.163845,0.032129,0.247942,1.513276,0.010898,1.111823
2,(frozen vegetables),(milk),0.095321,0.129583,0.023597,0.247552,1.910382,0.011245,1.156781
3,(frozen vegetables),(spaghetti),0.095321,0.174110,0.027863,0.292308,1.678867,0.011267,1.167018
4,(ground beef),(milk),0.098254,0.129583,0.021997,0.223881,1.727704,0.009265,1.121499
5,(spaghetti),(ground beef),0.174110,0.098254,0.039195,0.225115,2.291162,0.022088,1.163716
6,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997
7,(spaghetti),(milk),0.174110,0.129583,0.035462,0.203675,1.571779,0.012900,1.093043
8,(milk),(spaghetti),0.129583,0.174110,0.035462,0.273663,1.571779,0.012900,1.137061
9,(olive oil),(spaghetti),0.065858,0.174110,0.022930,0.348178,1.999758,0.011464,1.267048
10,(pancakes),(spaghetti),0.095054,0.174110,0.025197,0.265077,1.522468,0.008647,1.123778
11,(shrimp),(spaghetti),0.071457,0.174110,0.021197,0.296642,1.703760,0.008756,1.174209
12,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117

##### Results of Analysis
1. In looking at the rules, it seems that the ground beef and spaghetti are purchased together more often.
2. Milk and Chocolate, Frozen Vegetables and spaghetti, etc are purchased togetter more often.